name: nigerian_states_and_lga
description: A package that provides the list of all states and local goverments in Nigeria
version: 1.0.0
homepage: https://github.com/IdrisAdeyemi01/nigerian_states_and_lga.git

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

